language: android
jdk: oraclejdk8
sudo: required
services:
  - docker
android:
  components:
    # use the latest revision of Android SDK Tools
     - tools
     - platform-tools
     - tools
    # The BuildTools version used by your project
     - build-tools-26.0.2
    # The SDK version used to compile your project
     - android-26
     - android-22
     - extra-google-m2repository
     - extra-android-m2repository # for design library
before_install:
     - docker pull sinojelly/build-robolectric
     - docker run -d sinojelly/build-robolectric
     - docker ps -a
     - chmod +x gradlew

script:
  - ./gradlew test
  - ./gradlew lint



